steps:

############################################################################
# RUN UNIT TESTS
############################################################################

- name: python:2
  args: [
    'python', '-m', 'unittest', 'discover', '-s', 'cmd/', '-p', '*_test.py'
  ]

############################################################################
# BUILD ARTIFACTS
############################################################################

# TODO: enable once we can reconstruct .git directory using cbif.
## Pull in submodules to run jsonnet unit tests.
#- name: gcr.io/cloud-builders/git
#  args: [
#    'submodule', 'update', '--init', '--recursive'
#  ]

# Create the sjsonnet container for later steps.
- name: gcr.io/cloud-builders/docker
  args: [
    'build', '-t', 'jsonnet-env', '.'
  ]

# Generate v1 json files.
- name: jsonnet-env
  args: [
    'make'
  ]
  env:
   - 'PROJECT=${PROJECT_ID}'
   - 'VERSION=v1'

# Generate v2 json files.
- name: jsonnet-env
  args: [
    'make'
  ]
  env:
   - 'PROJECT=${PROJECT_ID}'
   - 'VERSION=v2'

############################################################################
# DEPLOY ARTIFACTS
############################################################################

# Publish new v1 data.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/v1/*', 'gs://siteinfo-$PROJECT_ID/v1/'
  ]

# Publish new v2 data.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/v2/*', 'gs://siteinfo-$PROJECT_ID/v2/'
  ]

# Copy v1 configs to archive.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/configs/v1/*', 'gs://siteinfo-$PROJECT_ID/configs/v1'
  ]

# Copy v2 configs to archive.
- name: gcr.io/cloud-builders/gsutil
  args: [
    '-h', 'Cache-Control:private, max-age=0, no-transform', '-m',
    'cp', '-r', '/workspace/output/configs/v2/*', 'gs://siteinfo-$PROJECT_ID/configs/v2'
  ]

############################################################################
# POST BUILD STEPS
############################################################################

# Run cloud build triggers in remote repos
#- name: gcr.io/cloud-builders/gcloud
#  entrypoint: '/bin/bash'
#  args: [
#    './run_remote_build_triggers.sh',
#    'epoxy-images-stage1',
#    'switch-config'
#  ]
#  env:
#  - 'PROJECT_ID=$PROJECT_ID'
#  - 'BRANCH_NAME=$BRANCH_NAME'

# Deploy the v1 primary measurement-lab.org zone to Cloud DNS.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: '/bin/bash'
  args: [
    './deploy_dns.sh'
  ]
  env:
  - 'PROJECT=${PROJECT_ID}'
  - 'DOMAIN=measurement-lab.org'
  - 'ZONEFILE=clouddns_measurement-lab.org.zone'
  - 'VERSION=v1'

# Deploy the v2 measurement-lab.org project subdomain zone to Cloud DNS
- name: gcr.io/cloud-builders/gcloud
  entrypoint: '/bin/bash'
  args: [
    './deploy_dns.sh'
  ]
  env:
  - 'PROJECT=${PROJECT_ID}'
  - 'DOMAIN=${PROJECT_ID}.measurement-lab.org'
  - 'ZONEFILE=${PROJECT_ID}.measurement-lab.org.zone'
  - 'VERSION=v2'
